import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ConfigProvider } from 'antd'
import { sequelize } from '@src/db'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  await sequelize.sync();
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigProvider componentSize='large' theme={{ token: { borderRadius: 4 } }}>
          {children}
        </ConfigProvider>
      </body>
    </html>
  )
}
